const {loadFixture,time}=require("@nomicfoundation/hardhat-toolbox/network-helpers");
const {expect}=require("chai");
const {anyValue}=require("@nomicfoundation/hardhat-chai-matchers/withArgs");

describe("Crowdfunding",function(){
 const goal=ethers.parseEther("2"),donation=ethers.parseEther("2");
 async function fixture(){const [creator,donor,donor2,outsider,...others]=await ethers.getSigners();const C=await ethers.getContractFactory("Crowdfunding"),c=await C.deploy(),deadline=(await time.latest())+604800;return{c,creator,donor,donor2,outsider,others,deadline}}
 async function create(c,creator,deadline,target=goal){await c.connect(creator).createProject("校园项目","项目描述","公益","https://example.com/cover.jpg",target,deadline)}

 it("creates and stores project metadata",async()=>{const{c,creator,deadline}=await loadFixture(fixture);await expect(c.connect(creator).createProject("校园项目","项目描述","公益","https://example.com/cover.jpg",goal,deadline)).to.emit(c,"ProjectCreated").withArgs(0,creator.address,"校园项目","项目描述","公益","https://example.com/cover.jpg",goal,deadline);expect((await c.getProject(0)).category).to.equal("公益")});
 it("records donations and early reward points",async()=>{const{c,creator,donor,deadline}=await loadFixture(fixture);await create(c,creator,deadline);await expect(c.connect(donor).donate(0,{value:donation})).to.emit(c,"EarlyDonorRewarded").withArgs(0,donor.address,100,anyValue);expect(await c.donations(0,donor.address)).to.equal(donation);expect(await c.rewardPointBalances(donor.address)).to.equal(100)});
 it("limits early rewards by time and first ten donors",async()=>{const{c,creator,donor,others,deadline}=await loadFixture(fixture);await create(c,creator,deadline);for(const a of others.slice(0,11))await c.connect(a).donate(0,{value:1n});expect((await c.getEarlyDonors(0)).length).to.equal(10);await time.increase(86401);await c.connect(donor).donate(0,{value:1n});expect(await c.getEarlyRewardPoints(0,donor.address)).to.equal(0)});
 it("finalizes successful and failed projects",async()=>{const{c,creator,donor,deadline}=await loadFixture(fixture);await create(c,creator,deadline);await c.connect(donor).donate(0,{value:donation});await time.increaseTo(deadline);await expect(c.endProject(0)).to.emit(c,"ProjectEnded").withArgs(0,true);expect((await c.getProject(0)).status).to.equal(1)});
 it("allows one-time creator withdrawal",async()=>{const{c,creator,donor,outsider,deadline}=await loadFixture(fixture);await create(c,creator,deadline);await c.connect(donor).donate(0,{value:donation});await time.increaseTo(deadline);await c.endProject(0);await expect(c.connect(outsider).withdrawFunds(0)).to.be.revertedWith("Only creator can withdraw");await c.connect(creator).withdrawFunds(0);await expect(c.connect(creator).withdrawFunds(0)).to.be.revertedWith("Funds already withdrawn")});
 it("refunds failed-project donors once",async()=>{const{c,creator,donor,deadline}=await loadFixture(fixture);await create(c,creator,deadline,ethers.parseEther("5"));await c.connect(donor).donate(0,{value:donation});await time.increaseTo(deadline);await c.endProject(0);await c.connect(donor).refund(0);expect(await c.donations(0,donor.address)).to.equal(0);await expect(c.connect(donor).refund(0)).to.be.revertedWith("No donation to refund")});
 it("requires donor majority approval for each milestone",async()=>{const{c,creator,donor,donor2,outsider,deadline}=await loadFixture(fixture);await create(c,creator,deadline);await c.connect(donor).donate(0,{value:donation/2n});await c.connect(donor2).donate(0,{value:donation/2n});expect(await c.requiredMilestoneVotes(0)).to.equal(2);await expect(c.connect(creator).releaseNextMilestone(0)).to.be.revertedWith("Milestone vote not approved");await c.connect(donor).voteForNextMilestone(0);await expect(c.connect(donor).voteForNextMilestone(0)).to.be.revertedWith("Already voted");await expect(c.connect(outsider).voteForNextMilestone(0)).to.be.revertedWith("Only donors can vote");await c.connect(donor2).voteForNextMilestone(0);await expect(c.connect(creator).releaseNextMilestone(0)).to.emit(c,"MilestoneReleased")});
 it("releases all four milestones after approvals",async()=>{const{c,creator,donor,deadline}=await loadFixture(fixture);await create(c,creator,deadline);await c.connect(donor).donate(0,{value:donation});for(let i=0;i<3;i++){await c.connect(donor).voteForNextMilestone(0);await c.connect(creator).releaseNextMilestone(0)}await time.increaseTo(deadline);await c.endProject(0);await c.connect(donor).voteForNextMilestone(0);await c.connect(creator).releaseNextMilestone(0);const p=await c.getProject(0);expect(p.milestonesCompleted).to.equal(4);expect(p.releasedAmount).to.equal(donation)});
 it("does not allow a successful project to start milestone mode",async()=>{const{c,creator,donor,deadline}=await loadFixture(fixture);await create(c,creator,deadline);await c.connect(donor).donate(0,{value:donation});await time.increaseTo(deadline);await c.endProject(0);await expect(c.connect(donor).voteForNextMilestone(0)).to.be.revertedWith("Project cannot use milestones")});
 it("releases goal-based milestone before deadline",async()=>{const{c,creator,donor,deadline}=await loadFixture(fixture),target=ethers.parseEther("4");await create(c,creator,deadline,target);await c.connect(donor).donate(0,{value:ethers.parseEther("0.9")});await expect(c.connect(donor).voteForNextMilestone(0)).to.be.revertedWith("Milestone threshold not reached");await c.connect(donor).donate(0,{value:ethers.parseEther("0.1")});await c.connect(donor).voteForNextMilestone(0);await expect(c.connect(creator).releaseNextMilestone(0)).to.emit(c,"MilestoneReleased").withArgs(0,creator.address,1,ethers.parseEther("1"),ethers.parseEther("1"))});
 it("refunds only unreleased pool proportionally",async()=>{const{c,creator,donor,donor2,deadline}=await loadFixture(fixture),target=ethers.parseEther("4");await create(c,creator,deadline,target);await c.connect(donor).donate(0,{value:ethers.parseEther("1")});await c.connect(donor2).donate(0,{value:ethers.parseEther("1")});await c.connect(donor).voteForNextMilestone(0);await c.connect(donor2).voteForNextMilestone(0);await c.connect(creator).releaseNextMilestone(0);await time.increaseTo(deadline);await c.endProject(0);expect((await c.getProject(0)).refundablePool).to.equal(ethers.parseEther("1"));expect(await c.getRefundableAmount(0,donor.address)).to.equal(ethers.parseEther("0.5"));await c.connect(donor).refund(0);await c.connect(donor2).refund(0);expect((await c.getProject(0)).refundablePool).to.equal(0)});
 it("redeems points for a memorial NFT and whitelist",async()=>{const{c,creator,donor,deadline}=await loadFixture(fixture);await create(c,creator,deadline);await c.connect(donor).donate(0,{value:donation});await expect(c.connect(donor).redeemRewardBadge()).to.emit(c,"RewardBadgeRedeemed").withArgs(donor.address,1,100);expect(await c.ownerOf(1)).to.equal(donor.address);expect(await c.rewardWhitelist(donor.address)).to.equal(true)});
 it("accumulates account points across projects",async()=>{const{c,creator,donor,deadline}=await loadFixture(fixture);await create(c,creator,deadline);await create(c,creator,deadline);await c.connect(donor).donate(0,{value:1n});await c.connect(donor).donate(1,{value:1n});expect(await c.rewardPointBalances(donor.address)).to.equal(200);await c.connect(donor).redeemRewardBadge();await c.connect(donor).redeemRewardBadge();expect(await c.balanceOf(donor.address)).to.equal(2)});
 it("cancels only empty projects by creator",async()=>{const{c,creator,outsider,deadline}=await loadFixture(fixture);await create(c,creator,deadline);await expect(c.connect(outsider).cancelProject(0)).to.be.revertedWith("Only creator can cancel");await c.connect(creator).cancelProject(0);expect((await c.getProject(0)).status).to.equal(3)});
});
